package com.mantkowicz.tg.enums;

public enum ScreenPhase 
{
	DOWNLOADING_JOBS,
	DOWNLOADING_USERS_LIST,
	DOWNLOADING_FONTS_LIST,
	DOWNLOADING_FONTS,
	DOWNLOADING_USERS,
	PLAYING,
	SENDING_OFFER,
	UPLOADING_OFFER,
	FINISHED, 
	IDLE
}
